export const ACTION_TYPES = {
  LOGIN: Symbol('LOGIN'),
  LOGIN_SUCCESS: Symbol('LOGIN_SUCCESS'),
  LOGIN_ERROR: Symbol('LOGIN_ERROR'),

  SET_IS_LOGIN: Symbol('SET_IS_LOGIN'),
  SET_LOGIN_ERROR_MESSAGE: Symbol('SET_LOGIN_ERROR_MESSAGE'),

  REGISTER_PHONE: Symbol('REGISTER_PHONE'),
  REGISTER_PHONE_SUCCESS: Symbol('REGISTER_PHONE_SUCCESS'),
  REGISTER_PHONE_ERROR: Symbol('REGISTER_PHONE_ERROR'),

  SET_IS_REGISTER_PHONE: Symbol('SET_IS_REGISTER_PHONE'),
  SET_IS_REGISTER_PHONE_SUCCESS: Symbol('SET_IS_REGISTER_PHONE_SUCCESS'),
  SET_REGISTER_PHONE_ERROR_MESSAGE: Symbol('SET_REGISTER_PHONE_ERROR_MESSAGE'),

  GET_PHONE_OTP: Symbol('GET_PHONE_OTP'),
  

  CONFIRM_PHONE_OTP: Symbol('CONFIRM_PHONE_OTP'),
  CONFIRM_PHONE_OTP_SUCCESS: Symbol('CONFIRM_PHONE_OTP_SUCCESS'),
  CONFIRM_PHONE_OTP_ERROR: Symbol('CONFIRM_PHONE_OTP_ERROR'),

  SET_IS_CONFIRM_PHONE: Symbol('SET_IS_CONFIRM_PHONE'),
  SET_IS_CONFIRM_PHONE_SUCCESS: Symbol('SET_IS_CONFIRM_PHONE_SUCCESS'),
  SET_CONFIRM_PHONE_ERROR_MESSAGE: Symbol('SET_CONFIRM_PHONE_ERROR_MESSAGE'),
};
