export const ACTION_TYPES = {
  SET_SEARCH_CONDITION: Symbol('SET_SEARCH_CONDITION'),

  SEARCH_PRODUCTS: Symbol('SEARCH_PRODUCTS'),
  SET_SEARCH_PRODUCTS: Symbol('SET_PRODUCTS'),

  SET_IS_SEARCHING: Symbol('SET_IS_SEARCHING'),
};
