export const ACTION_TYPES = {
  GET_PRODUCT_BY_ID: Symbol('GET_PRODUCT_BY_ID'),
  GET_PRODUCT_BY_ID_SUCCESS: Symbol('GET_PRODUCT_BY_ID_SUCCESS'),
  GET_PRODUCT_BY_ID_FAILURE: Symbol('GET_PRODUCT_BY_ID_FAILURE'),
};
