export const ACTION_TYPES = {
  CREATE_ZLP_ORDER_INFO: Symbol('CREATE_ZLP_ORDER_INFO'),
  CREATE_ZLP_ORDER_INFO_SUCCESS: Symbol('CREATE_ZLP_ORDER_INFO_SUCCESS'),
  CREATE_ZLP_ORDER_INFO_ERROR: Symbol('CREATE_ZLP_ORDER_INFO_ERROR'),
};
