export const ACTION_TYPES = {
  GET_MY_INFO: Symbol('GET_MY_INFO'),
  GET_MY_INFO_SUCCESS: Symbol('GET_MY_INFO_SUCCESS'),
  GET_MY_INFO_ERROR: Symbol('GET_MY_INFO_ERROR'),

  UPDATE_MY_INFO: Symbol('UPDATE_MY_INFO'),
  UPDATE_MY_INFO_SUCCESS: Symbol('UPDATE_MY_INFO_SUCCESS'),
  UPDATE_MY_INFO_ERROR: Symbol('UPDATE_MY_INFO_ERROR'),
};
