export const REACT_APP_ZALOPAY_BASE_URL =
  process.env.REACT_APP_ZALOPAY_BASE_URL;
// export const USER_SERVICES_BASE_URL = `${process.env.REACT_APP_BASE_FIRST_INSTANCE_URL}:81`;
// export const PRODUCT_SERVICES_BASE_URL = `${process.env.REACT_APP_BASE_FIRST_INSTANCE_URL}:82`;
export const USER_SERVICES_BASE_URL = `${process.env.REACT_APP_BASE_FIRST_INSTANCE_URL}:8000`;
